
modLoader="javafml" 
loaderVersion="[36,)" 
license="MIT"
[[mods]] 
modId="pupmod" 
version="1.8.1332115674200" 
displayName="PupMod" 
logoFile="pupmod_logo.png" 
credits="CreDITSSSS?????!!!" 
authors="leplopp" 
description='''
this is a nsoense Mod, for fun and fun, Hey have you FUN???
please....
HAVE...

FUN!!!
'''
[[dependencies.pupmod]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.pupmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
